Geometry 1D modifications
bendudson/hermes-3 pull request #232
Opened 2024-06-19 18:00 UTC by tbody-cfs

2025-04-30 15:26 UTC, tbody-cfs commented
# Test
![broadening](https://github.com/user-attachments/assets/10703713-3dd1-4223-b31d-23c549900d9a)

[evidence.zip](https://github.com/user-attachments/files/19980119/evidence.zip)

2025-05-01 21:19 UTC, tbody-cfs commented
One thing I've found — if the magnetic field doesn't equal the jacobian, we end up with a non-1 Jacobian. This has a small but noticeable impact on the simulation. Should the Jacobian be normalized such that it is 1 if the magnetic field is constant?
![image](https://github.com/user-attachments/assets/41d174ae-af6f-41de-a550-24dd2bfb1006)

2025-05-02 16:11 UTC, tbody-cfs commented
Full round of tests [test_fieldline_geometry.pdf](https://github.com/user-attachments/files/20015505/test_fieldline_geometry.pdf)

2025-06-03 13:56 UTC, mikekryjak commented
Hi @tbody-cfs, re your comment on May 1: I'm really confused as to why two simulations with different constant Jacobians would give a different answer. Are you 100% sure both simulations are fully steady state? That "step" which has the most difference looks like a density wave front which is not exactly in the same place in either simulation.

2025-06-03 14:40 UTC, mikekryjak requested changes
Hi @**Tom Body**, really great work on this - very nice clear code with lots of comments, and I really appreciate the docs as well as the test pdf you sent. Once this is merged, I think we should calculate some similar variables for 2D as well, that's been on my list for ages.

My comments are mostly about diagnostic naming and documentation location. 

I think it would also be really good if we had a proper test as we discussed at the dev meeting last week. Do you think this is something you have time to do? If not, then could you make a test by slapping some asserts in a Python script which will read the non-trivial formulation case?

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            state[std::string("fieldline_geometry_pitch_angle")], pitch_angle,
I think `pitch_angle` would be better as `magnetic_pitch`. I think it would be an angle if it was `theta` instead of `sin(theta)`.

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            {
I think this should be changed to `Rxy` to be consistent with BOUT++ nomenclature.

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            state[std::string("fieldline_geometry_poloidal_magnetic_field")], poloidal_magnetic_field,
Same for `B` as for `R`: we already have variables `Bxy`, `Bpxy`, `Btxy`. We should reuse those for consistency.

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            state[std::string("fieldline_geometry_flux_expansion")], flux_expansion,
`flux_expansion` is ambiguous because most people assume that to be poloidal flux expansion `f_x`  instead of total flux expansion `f_R`. I think it should be renamed to `f_R` as it's a commonly used abbreviation.

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            state[std::string("fieldline_geometry_cell_poloidal_length")], cell_poloidal_length,
This should be renamed `dlpol`, so that we have `dlpar`, `dlpol`, `lpar` and `lpol`. Ideally, I would prefer `s` instead of `l` as it's more precise notation and would be consistent with my existing 2D post-processing scripts (https://github.com/mikekryjak/sdtools/blob/d5b7a491476c979be143e3911fa6a7678460e829/hermes3/selectors.py#L109-L110) but happy to change mine instead since they're not yet in xHermes.

2025-06-03 14:40 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +            state[std::string("fieldline_geometry_cell_side_area")], cell_side_area,
I would say to rename this too but we don't have a name picked for this... let's keep it like this and rename later once we have a consistent cell face nomenclature in the future

2025-06-03 14:40 UTC, mikekryjak commented on docs/sphinx/fieldline_geometry.rst
> +Fieldline Geometry Component
I think the docs should live in the `Domain and gridding` section at the end. I also have minor edits to this docs page which I'll just do as a commit.

2026-06-30 17:54 UTC, tbody-cfs commented
Addressed @mikekryjak's review comments in e656907d:

- `pitch_angle` → `fieldline_geometry_magnetic_pitch`
- `fieldline_radius` → `fieldline_geometry_Rxy`
- `poloidal/toroidal/total_magnetic_field` → `fieldline_geometry_Bpxy` / `fieldline_geometry_Btxy` / `fieldline_geometry_Bxy`
- `flux_expansion` → `fieldline_geometry_f_R`
- `cell_poloidal_length` → `fieldline_geometry_dlpol`
- `cell_side_area` left as-is for now (no name agreed yet)
- Moved docs to immediately after `domain_grid` in the toctree

2026-06-30 20:10 UTC, tbody-cfs commented
Needs https://github.com/boutproject/hermes-3/pull/598 to pass clang-format test

2026-07-07 12:08 UTC, mikekryjak commented
Thanks @tbody-cfs, sorry I haven't had a chance to take a look yet - will do this week.

2026-07-08 09:44 UTC, mikekryjak requested changes
This is great work @tbody-cfs, especially the tests! I have a few questions, see below.

2026-07-08 09:44 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +        lpar(0, j, 0) = lpar(0, j - 1, 0) + 0.5 * dy(0, j - 1, 0) + 0.5 * dy(0, j, 0);
Have you tested this when running in parallel? This looks reasonable on a single rank, but presumably each rank after the first one would need to accumulate on the connection length from the previous ranks. But I don't see you using `id` for anything in this loop.

2026-07-08 09:44 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +  cell_volume = cell_side_area * flux_tube_width;
I see that none of the new geometry variables are put into the state for other components to read. Is this intentional? An easy way to do this would be to add code in `transform_impl` to put them into the state at every RHS. A better way would be to do it in the `coordinates` object, but that would be a BOUT++ change and it would be more complicated. I personally think the former is sufficient.

I know this is already being called by the new reservoirs - how does that work? @PoloidalLloyd

2026-07-08 09:44 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +    coord->Bxy[i] = std::numeric_limits<BoutReal>::quiet_NaN();
Hmm... I think `Bxy` almost certainly isn't used for any physics relevant to 1D simulations, but not 100% sure. @bendudson what do you think?

2026-07-08 16:27 UTC, tbody-cfs commented on src/fieldline_geometry.cxx
> +        lpar(0, j, 0) = lpar(0, j - 1, 0) + 0.5 * dy(0, j - 1, 0) + 0.5 * dy(0, j, 0);
Good catch — I tested this in the Docker image, running a non-trivial 1D case at 1, 4 and 8 ranks and comparing both the geometry outputs and the evolved solution cell-by-cell against the single-rank run. It surfaced two genuine parallel bugs.

On the loop itself / id: the accumulation is correct across ranks, but you're right that id wasn't doing anything. The mechanism is that each mesh->communicate(lpar) carries the running integral one rank downstream, so repeating the integrate-then-communicate step NYPE times propagates the value to every rank. id was just the repeat counter — I've renamed it sweep and documented that. I also fixed an off-by-one out-of-bounds write in the inner loop (j <= mesh->LocalNy → j < mesh->LocalNy). With this, lpar matches the single-rank result to machine precision.

Bug 1 — upstream reference used each rank's local first cell. Several quantities referenced field(0, mesh->ystart, 0), which is the local first cell, not the global upstream. So f_R, transport_broadening and Btor (with compute_Btor_from_R) — and hence the Jacobian — were only right on rank 0; every other rank restarted f_R at 1.0 at its local boundary:

f_R, np=4, first cells of each rank vs single-rank reference:
rank 0: [1.000 1.000 1.001 1.003]  ref [1.000 1.000 1.001 1.003]  ✓
rank 1: [1.000 0.997 0.994 0.991]  ref [1.849 1.843 1.837 1.830]  ✗
rank 2: [1.000 0.997 0.994 0.991]  ref [1.200 1.197 1.193 1.189]  ✗
rank 3: [1.000 1.000 0.999 0.998]  ref [1.016 1.016 1.015 1.015]  ✗

Fixed with an upstream_value() helper that reads the reference on rank 0 and MPI_Bcasts it. After this, all geometry outputs (lpar, Rxy, lambda_int, f_R, dlpol, Bxy) match the serial run to machine precision (max rel diff 0.0) at np = 1/4/8.

Bug 2 — coord->J was set only on interior cells. The geometry outputs matching wasn't sufficient: comparing the evolved solution showed a larger np1-vs-np4 spread for the default 1d-threshold case. The Jacobian was written only for ystart..yend, so the guard cells kept the default mesh J, discontinuous with the fieldline J. I now set J over the whole local field (guard cells included) and mesh->communicate(coord->J), mirroring recalculate_metric. Max relative np1-vs-np4 difference at a fixed output step:

field   before J-fix   after J-fix   1d-threshold
Ne         1.30%          0.57%          0.57%
Td         2.49%          1.49%          1.47%
Nd         1.60%          0.80%          0.80%

i.e. the fix brings the parallel spread down to the baseline the 1d-threshold already finds. Added a unit-test assertion that J is set in the guard cells (it fails against the old interior-only code).

On the residual difference: the ~0.5–1% that remains is not geometry-specific — the 1D-threshold shows the same, because this is the beuler steady-state solver at a fixed output step (snes_local_residual ~ 1e-3); the two decompositions take slightly different internal steps and land at slightly different points on a still-evolving transient. Driven to a tighter residual they converge to the same steady state.

2026-07-08 16:27 UTC, tbody-cfs commented on src/fieldline_geometry.cxx
> +  cell_volume = cell_side_area * flux_tube_width;
Not intentional — good suggestion, and I've taken the transform_impl approach you describe (agree the coordinates-object route is more invasive than it's worth here). transform_impl now publishes the geometry quantities into the shared state on every RHS, with matching readWrite permissions declared in the constructor, so other components can get<Field3D>() them. The keys mirror the diagnostic names — fieldline_geometry_Rxy, _Bxy, _lpar, _dlpol, _cell_volume, etc. Added a unit test (TransformPublishesGeometryToState) that checks all of them are published.

On the reservoirs — I don't have that component on this branch, so nothing consumes these yet here; this just makes them available. @PoloidalLloyd, could you confirm which keys the reservoir reads so I can make sure the names line up? Happy to rename to match whatever it expects.

2026-07-08 16:28 UTC, tbody-cfs commented on src/fieldline_geometry.cxx
> +    coord->Bxy[i] = std::numeric_limits<BoutReal>::quiet_NaN();
Looks like Bxy consumer is used in perpendicular-dynamics / turbulence / EM components (vorticity, the perpendicular operators in div_ops, diamagnetic & polarisation drifts, classical + ion/electron viscosity, neutral_full_velocity, electromagnetic, and the Alfvén-speed term in sound_speed)

2026-07-08 16:35 UTC, tbody-cfs commented
To test this out yourself @mikekryjak

# Testing `fieldline_geometry` in parallel with the Docker image

This walks through building the `geometry_1d` branch inside the
`ghcr.io/boutproject/hermes-3` image and verifying that a 1D
`fieldline_geometry` case gives the **same answer** regardless of the
y-decomposition (number of MPI ranks). Everything is copy-pasteable.

The idea: `nx=1` / `MXG=0` forces `NXPE=1`, so all MPI ranks split the field
line in `y` (`NYPE = np`). A correct component must give a decomposition-
independent result. We check two things:

1. the geometry output fields (`fieldline_geometry_*`) are identical across ranks;
2. the evolved solution (`Ne`, `Te`, …) matches the single-rank run to within the
   solver's own convergence floor (the 1D-threshold case sets that floor).

> **Prerequisites:** Docker (with `docker compose`), and a clone of hermes-3
> checked out on the `geometry_1d` branch. The published `:latest` image is built
> from `master`, so we build the branch code ourselves via the `work/hermes-3`
> override (steps 1–2).
>
> Multi-rank running (`run.sh hermes <case> <n>`) needs the parallel `run` mode
> that landed in #616, so make sure your image is current:
> `docker pull ghcr.io/boutproject/hermes-3:latest`. (If `./run.sh hermes
> work/case 4` logs `Processor number: 0 of 1`, your local image predates it.)
>
> All container commands go through the `docker/run.sh` helper, which wraps
> `docker compose`. It must be invoked from the `docker/` directory (it looks for
> `docker-compose.yaml` in the current directory), so every block below does
> `cd "$HERMES/docker"` first.

Pick your clone location once; every block below uses `$HERMES`:

```bash
export HERMES=$(git -C . rev-parse --show-toplevel)   # run from inside your clone
# ...or set it explicitly, e.g.  export HERMES=$HOME/hermes-3
cd "$HERMES" && git checkout geometry_1d
```

---

## 0. One-time setup

```bash
cd "$HERMES/docker"
sh setup.sh          # creates .env and the work/ mount (idempotent)
```

## 1. Stage the branch source into the build override

The image builds from `work/hermes-3` if present. Sync your checked-out branch
(and the googletest submodule, which the build needs for the unit tests) into it:

```bash
cd "$HERMES"
git submodule update --init external/googletest      # if not already populated
rsync -a --delete --exclude build/ --exclude .git/ ./ docker/work/hermes-3/
```

## 2. Build hermes-3 (with unit tests) in the container

Build **against the BOUT++ already compiled inside the image**
(`/hermes_project/build/boutpp-build`) — the branch only touches hermes-3
source, so there's no need to rebuild BOUT++. `HERMES_BUILD_BOUT=OFF` and
`HERMES_UPDATE_GIT_SUBMODULE=OFF` stop CMake from trying to re-fetch/rebuild the
bundled BOUT++ submodule (which fails, since we rsync'd without `.git/`):

```bash
cd "$HERMES/docker"
./run.sh shell bash -c '
  cmake -S /hermes_project/work/hermes-3 -B /hermes_project/work/hermes-3-build \
        -DCMAKE_PREFIX_PATH=/hermes_project/build/boutpp-build \
        -DHERMES_BUILD_BOUT=OFF -DHERMES_UPDATE_GIT_SUBMODULE=OFF \
        -DHERMES_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo &&
  cmake --build /hermes_project/work/hermes-3-build -j 4'
```

The executable lands at `/hermes_project/work/hermes-3-build/hermes-3`
(host: `docker/work/hermes-3-build/hermes-3`). The image's `run` mode picks up
this `work/hermes-3-build` override automatically.

## 3. Create the test cases (serial + parallel copies)

Start from the 1D-threshold case and add a **non-trivial** `[fieldline_geometry]`
section so the `{lpar}`-dependent expressions actually vary along the field line
(a constant geometry would pass trivially).

```bash
cd "$HERMES/docker/work"
for n in np1 np4; do
  rm -rf fieldline-par-$n
  cp -R "$HERMES/examples/tokamak-1D/1D-threshold" fieldline-par-$n
done
```

Two edits are needed in **both** `fieldline-par-np1/BOUT.inp` and
`fieldline-par-np4/BOUT.inp`.

**Edit 1 — enable the component.** In the `[hermes]` section, the 1D-threshold case has:

```ini
components = (d+, d, e,
              sheath_boundary_simple, braginskii_collisions, braginskii_friction,
              braginskii_heat_exchange, reactions, electron_force_balance,
              neutral_parallel_diffusion, braginskii_conduction, recycling)
```

Add `fieldline_geometry` as the **first** entry (component order matters — it must
set up the metric before the other components run):

```ini
components = (fieldline_geometry,
              d+, d, e,
              sheath_boundary_simple, braginskii_collisions, braginskii_friction,
              braginskii_heat_exchange, reactions, electron_force_balance,
              neutral_parallel_diffusion, braginskii_conduction, recycling)
```

**Edit 2 — configure it.** Append this section to the end of the file:

```ini
[fieldline_geometry]
# Non-trivial formulation to exercise the {lpar}-dependent expressions,
# which depend on the parallel-accumulated lpar being correct across ranks.
# mesh:length and mesh:length_xpt are already defined in the 1D-threshold case's
# [mesh] section, so no changes are needed there.
lpar_X1 = clamp( (mesh:length_xpt - {lpar}) / mesh:length_xpt, 0, 1)
lpar_X2 = clamp( ({lpar} - mesh:length_xpt) / (mesh:length - mesh:length_xpt), 0, 1)

lambda_q   = 1e-3
b          = 2.0
lambda_int = lambda_q * (1 + lpar_X2 * b)

poloidal_magnetic_field          = 1.0
upstream_toroidal_magnetic_field = 3.0
fieldline_radius = 0.5 + where({lpar} < mesh:length_xpt, 1 - cos(lpar_X1 * pi)/2, 1 - cos(lpar_X2 * pi)/2)

compute_Btor_from_R = true
diagnose            = true
```

That's all — the 1D-threshold case already sets `J = 1` in `[mesh]` (which
`fieldline_geometry` overrides) and defines `length`/`length_xpt`, so the
expressions above resolve without any further edits.

The stock example has `ny = 400`, which divides by 4, so np4 gives 100 interior
cells/rank. (If you change the rank count, use one that divides `ny`.)

## 4. Run at 1 and 4 ranks

`run.sh hermes <case> [n]` runs a case; the optional `n` is the MPI rank count
(default 1). It goes through the image's `run` mode, which launches `mpirun -np n`
(adding `--oversubscribe` automatically if `n` exceeds the cores Docker exposes):

```bash
cd "$HERMES/docker"
./run.sh hermes work/fieldline-par-np1 1
./run.sh hermes work/fieldline-par-np4 4
```

A correct 4-rank run logs `Running Hermes-3 in ... on 4 processes with mpirun`,
`Processor number: 0 of 4`, `NYPE=4`, and writes `BOUT.dmp.0.nc … BOUT.dmp.3.nc`
on the host under `docker/work/fieldline-par-np4/`.

> **Note — extra BOUT++ options.** The `run` mode only passes `-d <case>` to
> hermes-3; it does **not** forward trailing options such as `nout=10`. Put any
> such settings in the case's `BOUT.inp` instead (see the control in step 6).

## 5. Compare the runs

The image has `numpy` and `ncdump` but not xarray/netCDF4, so this small script
parses `ncdump` output. Save it as `docker/work/compare.py`:

```python
import subprocess, re, sys, glob, os
import numpy as np

def read_var(nc, var):
    out = subprocess.check_output(["ncdump", "-v", var, nc], text=True)
    m = re.search(re.escape(var) + r"\s*=\s*(.*?);", out, re.S)
    return np.array([float(x) for x in re.findall(r"[-+0-9.eE]+", m.group(1))])

def ydim(nc):
    out = subprocess.check_output(["ncdump", "-h", nc], text=True)
    return int(re.search(r"\by = (\d+)", out).group(1))

def field3d_vars(nc):
    # Match both time-evolving fields (t, x, y, z) and time-independent ones
    # (x, y, z) — the geometry outputs are constant in time and stored without
    # a time dimension.
    out = subprocess.check_output(["ncdump", "-h", nc], text=True)
    return re.findall(r"(?:double|float) (\w+)\((?:t, )?x, y, z\)", out)

serial_dir, par_dir = sys.argv[1], sys.argv[2]
f1 = os.path.join(serial_dir, "BOUT.dmp.0.nc")
fp = sorted(glob.glob(os.path.join(par_dir, "BOUT.dmp.*.nc")))
nf = len(fp)
assert nf > 1, "parallel dir must have >1 output file"

# Infer phy [...]

2026-07-16 20:31 UTC, tbody-cfs commented
@mikekryjak rebased onto latest main. Think this is good to go, and would be great to get it in while it's fresh

2026-07-17 08:52 UTC, mikekryjak commented on src/fieldline_geometry.cxx
> +  cell_volume = cell_side_area * flux_tube_width;
I talked to Lloyd and he will raise a separate PR to connect the reservoirs up.

2026-07-17 08:52 UTC, mikekryjak approved these changes
Good to go - thanks @tbody-cfs!

2026-07-17 08:53 UTC, merged